### ISSUE TITLE
How to uninstall it

### ISSUE THREAD

**Issue by little-dao** [mzdr/macOS#3]

**Comment by kdaveid** [comment]
Haven't needed that one but it would be interesting to know 👍

**Comment by mzdr** [comment]
Good question. Currently there is no way to "uninstall" it because I am not storing the old values before running the actual installation script. You should fork the project and remove anything you don’t like. 

I don’t feel like this is something this project needs, but feel free to provide a PR if you would consider this as important. Otherwise as stated in the README, fork and customize it to your personal taste and needs. 

Thanks for reaching out and apologies for responding so late. Sorry!
